name: CI + CD demo pipeline

# Define when the workflow should run. On a push to main, a PR to main or manually with workflow_dispatch

version: 2.1
jobs: 
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm test
          
      
    
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'ConfirmDeployment'
        
# Define some jobs that should run

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Compile on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.myapp.com'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SECRET_URL }}
    steps:
      - name: Deploy
        run: echo Your code is being deployed to dev.myapp.com!
      
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          channel: '#git-cicd'
          message: Build branch Successfully
        if: always()
        
# Our deployment to Staging environment job
  DeployStaging:
    name: Deploy to DeployStaging
    if: github.event.ref == 'refs/heads/main'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo Your code is being deployed to staging at http://test.myapp.com
  

# Our confirmation for deployment to production job
  ConfirmDeployment:
    name: Confirm Deployment
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'ConfirmDeployment'}}
    steps: 
      - name: Confirm Deployment to Production
        run: echo ${{ github.event.inputs.job == 'ConfirmDeployment'}}
        
        
# Our deployment to production job
  DeployProduction:
    name: Deploy to production
    needs: [ConfirmDeployment]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps: 
      - name: Deploy
        run: echo The app is live at http://www.myapp.com
